import type { Metadata } from "next";
import localFont from "next/font/local";




const pelak = localFont({
  src: "../../public/fonts/PelakFA-Black.ttf",
  variable: "--font-pelak",
  display: "swap",
  weight: "900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" className={` ${pelak.variable}`}>
      <body className={` ${pelak.className}`}>
        {children}
      </body>
    </html>
  );
}