import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/content/header";
import Footer from "@/components/content/footer";

export const metadata: Metadata = {
  title: "Fa Nia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="min-h-screen flex flex-col">
        <Header />
        <main className="grow">
          {children}
        </main>
        <div className="px-10 py-[46px]">
          <Footer />

        </div>
      </body>
    </html>
  );
}
